# Spring properties
spring:
  application:
     name: accounts

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration:18080/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port