# Spring properties
spring:
  application:
     name: accounts-service

  oauth2:
    resource:
      userInfoUri: http://localhost:2222/acc/user

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
  contextPath: /acc