# Spring properties
spring:
  application:
     name: accounts-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://xn--80aafhfrpg0adapheyc1nya.xn--p1ai:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port