plugins {
    id 'java'
    id 'application'
    id 'java-library'
}

group = 'com.jbrss'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    
    testCompileOnly 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
    
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    
    // RSS parsing
    api 'com.rometools:rome:2.1.0'
    implementation 'com.rometools:rome-utils:2.1.0'
}

test {
    useJUnitPlatform()
}

java {
}

application {
    mainClass = 'com.jbrss.Main'
}
