# Spring properties
spring:
  application:
     name: im-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration:18081/eureka/

# HTTP Server
server:
  port: 2233   # HTTP (Tomcat) port


jabber:
  server: terranz.mine.nu
  port: 5222
  user: jbrss
  pass: awd
  enable: true
telegram:
  botname: jbrssbot
  token: awd:a
  enable: true


oauth:
  resource: http://proxy:1111
  authorize: http://proxy:1111/acc/oauth/authorize
  token: http://proxy:1111/acc/oauth/token

authserver: http://proxy:1111/acc/
rssservice: http://proxy:1111/rss/