CREATE TABLE IF NOT EXISTS feedposts
(
  id          INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  feed_id     INTEGER      NOT NULL,
  isread      BIT          NOT NULL,
  postdate    DATETIME     NOT NULL,
  postlink    VARCHAR(128) NOT NULL,
  posttext    VARCHAR(128) NOT NULL,
  posttitle   VARCHAR(128) NOT NULL,
  update_time DATETIME     NOT NULL
);

CREATE TABLE IF NOT EXISTS feeds
(
  id          INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  feedname    VARCHAR(128) NOT NULL,
  feedurl     VARCHAR(128) NOT NULL,
  update_time DATETIME     NOT NULL
);


CREATE TABLE IF NOT EXISTS settings
(
  id     INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  skey   VARCHAR(128) NOT NULL,
  svalue VARCHAR(128) NOT NULL
);

