# Spring properties
spring:
  application:
     name: web-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2225   # HTTP (Tomcat) port

zuul:
  routes:
    ui:
      path: /**
      url: http://localhost:4200
    acc:
      path: /acc/**
      url: http://localhost:2222/acc