version: '2.2'

services:
    registration:
        image: jbrss/registration:latest
        ports:
          - 18081:18081
        mem_limit: 500000000
        healthcheck:
          test:  wget --quiet --tries=1 --spider http://localhost:18081/ || exit 1
          interval: 5s
          timeout: 10s
          retries: 60
    proxy:
        image: jbrss/proxy:latest
        ports:
          - 1111:1111
        depends_on:
          registration:
            condition: service_healthy
        mem_limit: 500000000
        healthcheck:
          test: wget --quiet --tries=1 --spider http://localhost:1111/env || exit 1
          interval: 1s
          timeout: 10s
          retries: 60
    accounts:
        image: jbrss/account:latest
        ports:
          - 2222:2222
        depends_on:
          proxy:
            condition: service_healthy
        mem_limit: 500000000
        healthcheck:
          test: wget -S --spider http://proxy:1111/accounts 2>&1 | grep 401 || exit 1
          interval: 5s
          timeout: 10s
          retries: 60
    rsscore:
        image: jbrss/rsscore:latest
        ports:
          - 2224:2224
        depends_on:
          accounts:
            condition: service_healthy
        mem_limit: 800000000
        healthcheck:
          test: wget -S --spider http://proxy:1111/rss 2>&1 | grep 401 || exit 1
          interval: 5s
          timeout: 10s
          retries: 60
    imapp:
        image: jbrss/imapp:latest
        ports:
          - 2233:2233
        depends_on:
          rsscore:
            condition: service_healthy
        mem_limit: 500000000
        healthcheck:
          test: wget -S --spider http://proxy:2233/rss 2>&1 | grep 401 || exit 1
          interval: 5s
          timeout: 10s
          retries: 60