spring:
  application:
     name: proxy

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration:18081/eureka/

server:
  port: 1111   # HTTP (Tomcat) port

zuul:
  routes:
    acc:
      path: /acc/**
      serviceId: ACCOUNTS
    rss:
      path: /rss/**
      service-id: RSSCORE
    ui:
      path: /jbrss/**
      url: http://localhost:4200/jbrss
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false