spring:
  application:
     name: proxy

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://xn--80aafhfrpg0adapheyc1nya.xn--p1ai:18080/eureka/

server:
  port: 1111   # HTTP (Tomcat) port

zuul:
  routes:
    acc:
      path: /acc/**
      serviceId: ACCOUNTS
    rss:
      path: /rss/**
      service-id: RSSCORE
    ui:
      path: /jbrss/**
      url: http://localhost:4200/jbrss