# Spring properties
spring:
  application:
     name: rsscore

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://85.113.55.84:18080/eureka/

# HTTP Server
server:
  port: 2224   # HTTP (Tomcat) port

oauth:
  resource: http://85.113.55.84:1111
  authorize: http://85.113.55.84:1111/acc/oauth/authorize
  token: http://85.113.55.84:1111/acc/oauth/token

authserver: http://85.113.55.84:1111/acc/