# Spring properties
spring:
  application:
     name: rsscore

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://xn--80aafhfrpg0adapheyc1nya.xn--p1ai:1111/eureka/

# HTTP Server
server:
  port: 2224   # HTTP (Tomcat) port

oauth:
  resource: http://xn--80aafhfrpg0adapheyc1nya.xn--p1ai:1111
  authorize: http://xn--80aafhfrpg0adapheyc1nya.xn--p1ai:1111/acc/oauth/authorize
  token: http://xn--80aafhfrpg0adapheyc1nya.xn--p1ai:1111/acc/oauth/token

authserver: http://xn--80aafhfrpg0adapheyc1nya.xn--p1ai:1111/acc/