# Spring properties
spring:
  application:
     name: rsscore-service

debug: true

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2224   # HTTP (Tomcat) port
  contextPath: /rss